name: 恢复5s-6s-sb-tnega服务并发送Telegram消息

on:
  schedule:
    - cron: '0 0 */1 * *'  # 每1天执行一次
  workflow_dispatch:

jobs:
  restore_and_notify:
    runs-on: ubuntu-22.04  # 指定使用 Ubuntu 22.04，避免使用 ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: 安装sshpass
        run: sudo apt-get install -y sshpass

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 执行Python脚本恢复5s-6s-sb-tnega服务并发送Telegram消息
        env:
          ACCOUNTS_JSON: ${{ secrets.ACCOUNTS_JSON }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python3 recover_5s-6s-sb-tnega.py
